apiVersion: v1
kind: Service
metadata:
  name: espocrm-mysql
  namespace: espocrm
  labels:
    app: espocrm-mysql
    component: database
spec:
  type: ClusterIP
  selector:
    app: espocrm-mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: espocrm-mysql-headless
  namespace: espocrm
  labels:
    app: espocrm-mysql
    component: database
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: espocrm-mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP