apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: espocrm-data-pvc
  namespace: espocrm
  labels:
    app: espocrm
    app.kubernetes.io/name: espocrm
    app.kubernetes.io/component: storage
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi