# Example secrets configuration for EspoCRM
# Copy this file to secrets.yaml and update with your values
# DO NOT commit secrets.yaml to git!

apiVersion: v1
kind: Secret
metadata:
  name: espocrm-mysql-secret
  namespace: espocrm
type: Opaque
stringData:
  root-password: "espocrm_root_password_2025"
  username: "espocrm"
  password: "espocrm_password_2025"
---
apiVersion: v1
kind: Secret
metadata:
  name: espocrm-admin-secret
  namespace: espocrm
type: Opaque
stringData:
  password: "admin_password_2025"
---
apiVersion: v1
kind: Secret
metadata:
  name: espocrm-api-secret
  namespace: espocrm
type: Opaque
stringData:
  api-key: "42a92c1380230c97b35eeaebab9ce57b"